//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QmaticDeneme.qmaticData {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QmaticWSSoap", Namespace="https://qmatic.koopbank.com/")]
    public partial class QmaticWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActiveReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveReservationBranchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveReservationTicketTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReservationSlotsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveBranchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMainRangeReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMainBranchRangeReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDailySubReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QmaticWS() {
            this.Url = global::QmaticDeneme.Properties.Settings.Default.QmaticDeneme_qmaticData_QmaticWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event ActiveReservationCompletedEventHandler ActiveReservationCompleted;
        
        /// <remarks/>
        public event GetActiveReservationBranchesCompletedEventHandler GetActiveReservationBranchesCompleted;
        
        /// <remarks/>
        public event GetActiveReservationTicketTypesCompletedEventHandler GetActiveReservationTicketTypesCompleted;
        
        /// <remarks/>
        public event GetReservationSlotsCompletedEventHandler GetReservationSlotsCompleted;
        
        /// <remarks/>
        public event CreateReservationCompletedEventHandler CreateReservationCompleted;
        
        /// <remarks/>
        public event GetActiveBranchesCompletedEventHandler GetActiveBranchesCompleted;
        
        /// <remarks/>
        public event GetMainRangeReportCompletedEventHandler GetMainRangeReportCompleted;
        
        /// <remarks/>
        public event GetMainBranchRangeReportCompletedEventHandler GetMainBranchRangeReportCompleted;
        
        /// <remarks/>
        public event GetDailySubReportCompletedEventHandler GetDailySubReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/Test", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test(string input) {
            object[] results = this.Invoke("Test", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync(string input) {
            this.TestAsync(input, null);
        }
        
        /// <remarks/>
        public void TestAsync(string input, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        input}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/ActiveReservation", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActiveReservation(string reservationCode, int subnet, string reservationActivationCode) {
            object[] results = this.Invoke("ActiveReservation", new object[] {
                        reservationCode,
                        subnet,
                        reservationActivationCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActiveReservationAsync(string reservationCode, int subnet, string reservationActivationCode) {
            this.ActiveReservationAsync(reservationCode, subnet, reservationActivationCode, null);
        }
        
        /// <remarks/>
        public void ActiveReservationAsync(string reservationCode, int subnet, string reservationActivationCode, object userState) {
            if ((this.ActiveReservationOperationCompleted == null)) {
                this.ActiveReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActiveReservationOperationCompleted);
            }
            this.InvokeAsync("ActiveReservation", new object[] {
                        reservationCode,
                        subnet,
                        reservationActivationCode}, this.ActiveReservationOperationCompleted, userState);
        }
        
        private void OnActiveReservationOperationCompleted(object arg) {
            if ((this.ActiveReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActiveReservationCompleted(this, new ActiveReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetActiveReservationBranches", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_BranchDto[] GetActiveReservationBranches() {
            object[] results = this.Invoke("GetActiveReservationBranches", new object[0]);
            return ((Qmatic_BranchDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveReservationBranchesAsync() {
            this.GetActiveReservationBranchesAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveReservationBranchesAsync(object userState) {
            if ((this.GetActiveReservationBranchesOperationCompleted == null)) {
                this.GetActiveReservationBranchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveReservationBranchesOperationCompleted);
            }
            this.InvokeAsync("GetActiveReservationBranches", new object[0], this.GetActiveReservationBranchesOperationCompleted, userState);
        }
        
        private void OnGetActiveReservationBranchesOperationCompleted(object arg) {
            if ((this.GetActiveReservationBranchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveReservationBranchesCompleted(this, new GetActiveReservationBranchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetActiveReservationTicketTypes", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_ButtonDto[] GetActiveReservationTicketTypes(int subnet) {
            object[] results = this.Invoke("GetActiveReservationTicketTypes", new object[] {
                        subnet});
            return ((Qmatic_ButtonDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveReservationTicketTypesAsync(int subnet) {
            this.GetActiveReservationTicketTypesAsync(subnet, null);
        }
        
        /// <remarks/>
        public void GetActiveReservationTicketTypesAsync(int subnet, object userState) {
            if ((this.GetActiveReservationTicketTypesOperationCompleted == null)) {
                this.GetActiveReservationTicketTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveReservationTicketTypesOperationCompleted);
            }
            this.InvokeAsync("GetActiveReservationTicketTypes", new object[] {
                        subnet}, this.GetActiveReservationTicketTypesOperationCompleted, userState);
        }
        
        private void OnGetActiveReservationTicketTypesOperationCompleted(object arg) {
            if ((this.GetActiveReservationTicketTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveReservationTicketTypesCompleted(this, new GetActiveReservationTicketTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetReservationSlots", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_ReservationSlotDto[] GetReservationSlots(int subnet, int button_ID) {
            object[] results = this.Invoke("GetReservationSlots", new object[] {
                        subnet,
                        button_ID});
            return ((Qmatic_ReservationSlotDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReservationSlotsAsync(int subnet, int button_ID) {
            this.GetReservationSlotsAsync(subnet, button_ID, null);
        }
        
        /// <remarks/>
        public void GetReservationSlotsAsync(int subnet, int button_ID, object userState) {
            if ((this.GetReservationSlotsOperationCompleted == null)) {
                this.GetReservationSlotsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReservationSlotsOperationCompleted);
            }
            this.InvokeAsync("GetReservationSlots", new object[] {
                        subnet,
                        button_ID}, this.GetReservationSlotsOperationCompleted, userState);
        }
        
        private void OnGetReservationSlotsOperationCompleted(object arg) {
            if ((this.GetReservationSlotsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReservationSlotsCompleted(this, new GetReservationSlotsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/CreateReservation", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateReservation(System.DateTime reserveDate, int slotID, string clientID, string musteriNo, string kartNo, string cepTel) {
            object[] results = this.Invoke("CreateReservation", new object[] {
                        reserveDate,
                        slotID,
                        clientID,
                        musteriNo,
                        kartNo,
                        cepTel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateReservationAsync(System.DateTime reserveDate, int slotID, string clientID, string musteriNo, string kartNo, string cepTel) {
            this.CreateReservationAsync(reserveDate, slotID, clientID, musteriNo, kartNo, cepTel, null);
        }
        
        /// <remarks/>
        public void CreateReservationAsync(System.DateTime reserveDate, int slotID, string clientID, string musteriNo, string kartNo, string cepTel, object userState) {
            if ((this.CreateReservationOperationCompleted == null)) {
                this.CreateReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateReservationOperationCompleted);
            }
            this.InvokeAsync("CreateReservation", new object[] {
                        reserveDate,
                        slotID,
                        clientID,
                        musteriNo,
                        kartNo,
                        cepTel}, this.CreateReservationOperationCompleted, userState);
        }
        
        private void OnCreateReservationOperationCompleted(object arg) {
            if ((this.CreateReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateReservationCompleted(this, new CreateReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetActiveBranches", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_Branch[] GetActiveBranches() {
            object[] results = this.Invoke("GetActiveBranches", new object[0]);
            return ((Qmatic_Branch[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveBranchesAsync() {
            this.GetActiveBranchesAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveBranchesAsync(object userState) {
            if ((this.GetActiveBranchesOperationCompleted == null)) {
                this.GetActiveBranchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveBranchesOperationCompleted);
            }
            this.InvokeAsync("GetActiveBranches", new object[0], this.GetActiveBranchesOperationCompleted, userState);
        }
        
        private void OnGetActiveBranchesOperationCompleted(object arg) {
            if ((this.GetActiveBranchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveBranchesCompleted(this, new GetActiveBranchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetMainRangeReport", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_DailyMainReport[] GetMainRangeReport(System.DateTime startDate, System.DateTime endDate, string reportType) {
            object[] results = this.Invoke("GetMainRangeReport", new object[] {
                        startDate,
                        endDate,
                        reportType});
            return ((Qmatic_DailyMainReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMainRangeReportAsync(System.DateTime startDate, System.DateTime endDate, string reportType) {
            this.GetMainRangeReportAsync(startDate, endDate, reportType, null);
        }
        
        /// <remarks/>
        public void GetMainRangeReportAsync(System.DateTime startDate, System.DateTime endDate, string reportType, object userState) {
            if ((this.GetMainRangeReportOperationCompleted == null)) {
                this.GetMainRangeReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMainRangeReportOperationCompleted);
            }
            this.InvokeAsync("GetMainRangeReport", new object[] {
                        startDate,
                        endDate,
                        reportType}, this.GetMainRangeReportOperationCompleted, userState);
        }
        
        private void OnGetMainRangeReportOperationCompleted(object arg) {
            if ((this.GetMainRangeReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMainRangeReportCompleted(this, new GetMainRangeReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetMainBranchRangeReport", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_DailyMainReport[] GetMainBranchRangeReport(int branchSubnet, System.DateTime startDate, System.DateTime endDate, string reportType) {
            object[] results = this.Invoke("GetMainBranchRangeReport", new object[] {
                        branchSubnet,
                        startDate,
                        endDate,
                        reportType});
            return ((Qmatic_DailyMainReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMainBranchRangeReportAsync(int branchSubnet, System.DateTime startDate, System.DateTime endDate, string reportType) {
            this.GetMainBranchRangeReportAsync(branchSubnet, startDate, endDate, reportType, null);
        }
        
        /// <remarks/>
        public void GetMainBranchRangeReportAsync(int branchSubnet, System.DateTime startDate, System.DateTime endDate, string reportType, object userState) {
            if ((this.GetMainBranchRangeReportOperationCompleted == null)) {
                this.GetMainBranchRangeReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMainBranchRangeReportOperationCompleted);
            }
            this.InvokeAsync("GetMainBranchRangeReport", new object[] {
                        branchSubnet,
                        startDate,
                        endDate,
                        reportType}, this.GetMainBranchRangeReportOperationCompleted, userState);
        }
        
        private void OnGetMainBranchRangeReportOperationCompleted(object arg) {
            if ((this.GetMainBranchRangeReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMainBranchRangeReportCompleted(this, new GetMainBranchRangeReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://qmatic.koopbank.com/GetDailySubReport", RequestNamespace="https://qmatic.koopbank.com/", ResponseNamespace="https://qmatic.koopbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Qmatic_DailySubReport[] GetDailySubReport(int ticketSubnet, System.DateTime startDate, System.DateTime endDate, string reportType) {
            object[] results = this.Invoke("GetDailySubReport", new object[] {
                        ticketSubnet,
                        startDate,
                        endDate,
                        reportType});
            return ((Qmatic_DailySubReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDailySubReportAsync(int ticketSubnet, System.DateTime startDate, System.DateTime endDate, string reportType) {
            this.GetDailySubReportAsync(ticketSubnet, startDate, endDate, reportType, null);
        }
        
        /// <remarks/>
        public void GetDailySubReportAsync(int ticketSubnet, System.DateTime startDate, System.DateTime endDate, string reportType, object userState) {
            if ((this.GetDailySubReportOperationCompleted == null)) {
                this.GetDailySubReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDailySubReportOperationCompleted);
            }
            this.InvokeAsync("GetDailySubReport", new object[] {
                        ticketSubnet,
                        startDate,
                        endDate,
                        reportType}, this.GetDailySubReportOperationCompleted, userState);
        }
        
        private void OnGetDailySubReportOperationCompleted(object arg) {
            if ((this.GetDailySubReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDailySubReportCompleted(this, new GetDailySubReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_BranchDto {
        
        private int subnetField;
        
        private string branchNameField;
        
        /// <remarks/>
        public int Subnet {
            get {
                return this.subnetField;
            }
            set {
                this.subnetField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_DailySubReport {
        
        private string referenceDateField;
        
        private string referenceNameField;
        
        private int totalTicketField;
        
        /// <remarks/>
        public string ReferenceDate {
            get {
                return this.referenceDateField;
            }
            set {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        public int TotalTicket {
            get {
                return this.totalTicketField;
            }
            set {
                this.totalTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_DailyMainReport {
        
        private string referenceDateField;
        
        private int ticketSubnetField;
        
        private string referenceNameField;
        
        private int totalTicketField;
        
        /// <remarks/>
        public string ReferenceDate {
            get {
                return this.referenceDateField;
            }
            set {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        public int TicketSubnet {
            get {
                return this.ticketSubnetField;
            }
            set {
                this.ticketSubnetField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        public int TotalTicket {
            get {
                return this.totalTicketField;
            }
            set {
                this.totalTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_Branch {
        
        private int branchIDField;
        
        private string branchNameField;
        
        private int branchSubnetField;
        
        private bool isActiveField;
        
        private string backgroundImagePathField;
        
        private string labelColorField;
        
        private int forceQmaticUpdateField;
        
        private int forceMonitorUpdateField;
        
        private int forceRestartField;
        
        private int reservationFlagField;
        
        /// <remarks/>
        public int BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public int BranchSubnet {
            get {
                return this.branchSubnetField;
            }
            set {
                this.branchSubnetField = value;
            }
        }
        
        /// <remarks/>
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string BackgroundImagePath {
            get {
                return this.backgroundImagePathField;
            }
            set {
                this.backgroundImagePathField = value;
            }
        }
        
        /// <remarks/>
        public string LabelColor {
            get {
                return this.labelColorField;
            }
            set {
                this.labelColorField = value;
            }
        }
        
        /// <remarks/>
        public int ForceQmaticUpdate {
            get {
                return this.forceQmaticUpdateField;
            }
            set {
                this.forceQmaticUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int ForceMonitorUpdate {
            get {
                return this.forceMonitorUpdateField;
            }
            set {
                this.forceMonitorUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int ForceRestart {
            get {
                return this.forceRestartField;
            }
            set {
                this.forceRestartField = value;
            }
        }
        
        /// <remarks/>
        public int ReservationFlag {
            get {
                return this.reservationFlagField;
            }
            set {
                this.reservationFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_ReservationSlotDto {
        
        private int slotIDField;
        
        private string timeRangeField;
        
        /// <remarks/>
        public int SlotID {
            get {
                return this.slotIDField;
            }
            set {
                this.slotIDField = value;
            }
        }
        
        /// <remarks/>
        public string TimeRange {
            get {
                return this.timeRangeField;
            }
            set {
                this.timeRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://qmatic.koopbank.com/")]
    public partial class Qmatic_ButtonDto {
        
        private int buttonIDField;
        
        private string buttonNameField;
        
        private string ticketTypeField;
        
        private int counterStartField;
        
        private int counterEndField;
        
        /// <remarks/>
        public int ButtonID {
            get {
                return this.buttonIDField;
            }
            set {
                this.buttonIDField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonName {
            get {
                return this.buttonNameField;
            }
            set {
                this.buttonNameField = value;
            }
        }
        
        /// <remarks/>
        public string TicketType {
            get {
                return this.ticketTypeField;
            }
            set {
                this.ticketTypeField = value;
            }
        }
        
        /// <remarks/>
        public int CounterStart {
            get {
                return this.counterStartField;
            }
            set {
                this.counterStartField = value;
            }
        }
        
        /// <remarks/>
        public int CounterEnd {
            get {
                return this.counterEndField;
            }
            set {
                this.counterEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ActiveReservationCompletedEventHandler(object sender, ActiveReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActiveReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActiveReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetActiveReservationBranchesCompletedEventHandler(object sender, GetActiveReservationBranchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveReservationBranchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveReservationBranchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_BranchDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_BranchDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetActiveReservationTicketTypesCompletedEventHandler(object sender, GetActiveReservationTicketTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveReservationTicketTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveReservationTicketTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_ButtonDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_ButtonDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetReservationSlotsCompletedEventHandler(object sender, GetReservationSlotsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReservationSlotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReservationSlotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_ReservationSlotDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_ReservationSlotDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateReservationCompletedEventHandler(object sender, CreateReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetActiveBranchesCompletedEventHandler(object sender, GetActiveBranchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveBranchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveBranchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_Branch[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_Branch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMainRangeReportCompletedEventHandler(object sender, GetMainRangeReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMainRangeReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMainRangeReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_DailyMainReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_DailyMainReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMainBranchRangeReportCompletedEventHandler(object sender, GetMainBranchRangeReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMainBranchRangeReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMainBranchRangeReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_DailyMainReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_DailyMainReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDailySubReportCompletedEventHandler(object sender, GetDailySubReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDailySubReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDailySubReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Qmatic_DailySubReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Qmatic_DailySubReport[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591